Awesome Books
cyrilmuchemi/Awesome-Books pull request #1
Opened 2022-04-18 22:40 UTC by cyrilmuchemi

- This is a simple HTML website for testing various javaScript Skills.
- My partner @SiansandaTamara and I, have implemented javascript methods and objects to add and remove books from this simple app.

2022-04-19 15:58 UTC, topeogunleye requested changes
> # Changes Required 
> ### Hi @cyrilmuchemi,
> Nice job, you are almost there.
> 
> ![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)
> 
> ## (Highlights) Good Points: 
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
> * Professional README file. :heavy_check_mark:
>
> ## (Changes Required) Aspects to improve: 
> * [ ]  Please follow the wireframe and put the booklist before the form
> ![Screenshot from 2022-04-19 16-52-03](https://user-images.githubusercontent.com/52934128/164045384-33ca99de-6b80-4668-bbaa-bb58d6fdf7d3.png)
> Wireframe:
> <img width="437" alt="book-form" src="https://user-images.githubusercontent.com/52934128/164045808-bac812e4-de51-497d-8d74-59cea6b58113.png">

> ## [Optional] suggestions:
> * Nothing to mention
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> **Cheers and Happy coding! :clap::clap::clap:**
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear
> Please, remember to tag @topeogunleye in your question so I can receive the notification.
>
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-19 15:58 UTC, topeogunleye commented on app.js
> +  static removeBook(author) {
- [ ] [REQUIRED] I can see that your method to remove books from local storage is not working. Please kindly fix this

https://user-images.githubusercontent.com/52934128/164044395-0c0c6272-a36b-4d02-bcbb-63bc5e0f206f.mp4

2022-04-19 19:00 UTC, Kingstalux commented on app.js
> +  static removeBook(author) {
resolved

2022-04-19 19:04 UTC, cyrilmuchemi commented on app.js
> +  static removeBook(author) {
@Kingstalux , what's the review?

2022-04-19 19:09 UTC, Kingstalux requested changes
Hi @team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✅ App works as expected 🔥 
✅ Linters are passing 👏 
✅ Good commit messages 👍 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-20 11:17 UTC, OLIPLICHE approved these changes
Hi @cyrilmuchemi , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-20 11:19 UTC, merged

2022-04-20 11:48 UTC, topeogunleye commented on app.js
> +  static removeBook(author) {
Great 👍🏿