JavaScript With ES6 syntax
cyrilmuchemi/Awesome-Books pull request #2
Opened 2022-04-25 09:59 UTC by cyrilmuchemi

- In this project, I have refactored my Awesome books project to use ES6 syntax

2022-04-25 10:11 UTC, mikethreels requested changes
Hi Cyril, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-25 10:11 UTC, mikethreels commented on index.js
> +};
- [ ] according to the requirements you should Create a directory called modules. and Divide your code into modules. Save each module in a separate file in the modules dir. Import modules in the index.js file. For this exercise - the more modules the better! please do so before requesting another review.

2022-04-25 10:11 UTC, mikethreels commented on index.js
> +};
- [ ] The current date which is displayed below the navigation bar, for this requirement, you should use the [Luxon](https://github.com/moment/luxon/blob/master/docs/install.md) library. See [Get the current date and time](https://github.com/moment/luxon/blob/master/docs/tour.md#get-the-current-date-and-time) for more details.

- Package is added as a .js file to the project (in full or minified version)
- Module is imported import { DateTime } from "luxon";

2022-04-25 10:11 UTC, mikethreels commented on README.md
> +[Live Demo Link](https://siansandatamara.github.io/framework-awesomebook/)
- [ ] please make sure to use [the template](https://github.com/microverseinc/readme-template) for the readme file provided by Microverse, including the links (for example to the MIT license). keep in mind that all sections of the template are mandatory except for the "Live Demo", "Run Tests" and "Deployment" sections, these are only mandatory if the specific project you're working on requires it.

2022-04-26 12:52 UTC, dasileker requested changes
### **Hi @cyrilmuchemi,** 

### **Great work on making the changes 👏** 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## **Suggested changes**
_Check the comments under the review._

- **Hello mate as the previous tse said the requirements state that the files should be divided. please make sure to submit the PR after completing all requirements.**

![Capture web_26-4-2022_125030_github com](https://user-images.githubusercontent.com/61562626/165303959-b69bc563-fec1-43ef-8cde-8a45d50a6151.jpeg)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-04-26 13:07 UTC, keroloussamy approved these changes
Hi @cyrilmuchemi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️
- Add all the requirements. ✔️

![clap](https://media0.giphy.com/media/j2GPljpvL8Lulm3d0X/giphy.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-26 13:10 UTC, merged